image: python:latest

services:
  - postgres:latest
  - redis:latest

variables:
  POSTGRES_DB: ci
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: trust

# This folder is cached between builds
# http://docs.gitlab.com/ee/ci/yaml/README.html#cache
cache:
  paths:
    - ~/.cache/pip/

before_script:
  - python -V  # print python version for debugging
  - pip install -r requirements.txt

test:
  variables:
    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"
  script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - python manage.py makemigrations --settings bitpin.settings_ci
    - python manage.py migrate --settings bitpin.settings_ci
    - python manage.py test --settings bitpin.settings_ci
  only:
    - main
